### ISSUE TITLE
Conflicts with no-peeping-toms plugin

### ISSUE THREAD

**Issue by skiz** [pluginaweek/state_machine#1]
I have come across some serious issues with using the no-peeping-toms plugin along with the state machine plugin.  If you have any state machine configured in any loaded file, then the no-peeping system breaks, and also the specs fail.  I am working on a solution to this but wanted to note it on both repositories. Perhaps someone else may come up with a fix first.

**Comment by obrie** [comment]
Figured I'd comment on this since I don't think this issue was ever filed on lighthouse.  This should be fixed in the latest version of no-peeping-toms (2.0+).  The problem was that no-peeping-toms was overriding Observer hooks in a way that was incompatible with how state_machine was using those hooks.

**Comment by skiz** [comment]
Excellent, thanks for the update.
