### ISSUE TITLE
State-Scopes in ActiveRecord 3

### ISSUE THREAD

**Issue by salzig** [pluginaweek/state_machine#107]
Sadly State-Scopes seem to be limited to ActiveRecord 2
https://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/integrations/active_record/versions.rb

would be nice if someone could take some time to implement them for version 3

**Comment by obrie** [comment]
State scopes are supported in ActiveRecord 3 -- see https://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/integrations/active_record.rb#L428.

**Comment by flatrocks** [comment]
I am extremely reluctant to make this comment because there is always the possibility that I am being a bonehead, and because this issue has already been closed.  But as far as I can tell, the "scope" behavior does not seem to work at all for ActiveRecord objects in Rails 3.2.  I am talking about the **with_state()** method described at:
http://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/integrations/active_record.rb

I've got a model including state_machine:

```
class CsvImport < ActiveRecord::Base 
  ...
  # :new => :working => [:failed, :canceled, :succeeded]
  state_machine :import_state, namespace: 'importing', :initial => :new do
    event :start do
      transition :new => :working
    end
    event :continue do
      transition :working => same
    end
    event :succeed do
      transition :working => :succeeded
    end
    event :fail do
      transition any => :failed
    end
    event :cancel do
      transition any => :canceled
    end
  end
  ...
end
```

But the "with_state" method does not seem to work at all:

```
irb(main):003:0> CsvImport.with_state(:working)
NoMethodError: undefined method `with_state' for #<Class:0x007fe51f6d2200>
```

I've cloned the repo hoping to learn what I was doing wrong by running/examining the tests, but (as far as I can tell, working with and around all the "Appraisal" business related to different environments,) the test coverage does not seem to hit the related tests for **with_state**, and I didn't learn anything new.

I apologize if I am just being a knucklehead, but it seems like either the "scope" functionality is not working, or there's something that could be clearer in the docs on how to access it.  I will say I am not the first person to wonder about this:
http://stackoverflow.com/questions/14824134/returning-all-records-in-a-certain-state-with-state-machine

Using 

```
CsvImport.with_state(:working)
```

is really only a little better than

```
CsvImport.where(import_state: 'working')
```

but I _have_ spent a lot of time now wondering why the first option doesn't work...  if I am missing something basic I think it might at least warrant some help in the docs/comments.

**Comment by twalpole** [comment]
Since your state machine is named import_state you want  CavImport.with_import_state or CavImport.with_import_states  .  Easy way to check that is by doing CavImport.methods.grep /^with/ in the console

**Comment by flatrocks** [comment]
D'oh! (and Thank You!)
I had gone as far as listing all the CsvImport methods to a text doc to pore through them... but had apparently used CsvImport.class.methods and/or CsvImport.instance_methods, everything I could think of but the right thing.

**:with_import_state, :without_import_state, :with_import_states, :without_import_states** are all available as advertised.  (Listing here for the next poor soul who overlooks the application of the namespace to the scope methods.)
