### ISSUE TITLE
Getting ActionView::Template::Error: undefined method `state' for #<Listing:0x0000010aa8f880>

### ISSUE THREAD

**Issue by tsemana** [pluginaweek/state_machine#110]
I'm getting the above error on my views when I call <#= @model.human_state_name %>  but in my unit tests work, and this assertion @model.state.should be == "good state" in my integration test works.  The test where this the assertion works also calls the view where I'm trying to get the name and that's where it fails on the view..  the view can get all other attribute of @model as is expected

using rails 3.1.0rc5, state_machine 1.0.2

**Comment by tsemana** [comment]
I got that working by adding attr_accessor :state.  Now having an issue with FactoryGirl and that it doesn't seem to set the initial state properly.  I've found this answer, but I have not gotten it to work http://stackoverflow.com/questions/5728584/testing-dynamic-initial-states-with-factorygirl-and-statemachine.

currently, I'm setting up the model now without an initial state, but the before_validation line is blocking me, since when I call self.inital! (which is my transition to go from Nil to 'draft') I receive the response that I can't transition using initial _from_ draft.  Very confused now..

**Comment by obrie** [comment]
Hi tsemana,

Thanks for reporting this.  Unfortunately, it'll be very difficult to debug your issues without a little more context.  Specifically, I'd like to see:
- Your model's state_machine definition
- Your model's database schema
- The test you're running (and any before / setup hooks)

Ideally, I'd like to be able to run the test on my machine so that I can investigate the error.  The only thing I'd say is that you should **not** need to add `attr_accessor :state` in order to get this working.  `state` should already be a column in your database.  If it's not, then I'd start there.  If it is, then my suspicion is that some other library (like a mocking library) is changing the behavior of your class.

Once you've tested that out, I'd chang your view to call `@model.state` instead of `@model.human_state_name`.  This will allow you to skip state_machine altogether and go straight to your model so that you can ensure that the attribute does indeed exist.  If this also causes the exception, then you can be sure it's not a problem with state_machine.

With regard to FactoryGirl, I've updated the documentation to explain the incompatibility and a few workarounds: https://github.com/pluginaweek/state_machine/commit/01ea7de1a0a73c7784f79a318956679bad4c214f

Finally, for understanding why you can't transition from `nil` to `draft`, I would suggest reading through the validation errors on your object.  Events can fail for many reasons, one of them being that a validation fails.  To do this, simply call your event without a bang (!), and inspect the `errors` attribute on your object.

Hope this helps!  Please let me know what you find out so that we can determine whether to close this issue or not.

**Comment by tsemana** [comment]
Thanks for the reply.  I had since moved to another state_machine implementation just so I could deliver something today, but I branched that version of the code so that I could go back to it.  I'll work through your suggestions hopefully this weekend and get back to you.

regards,
Tony

**Comment by obrie** [comment]
Sounds good, Tony!  I'm going to close this issue for now, but please re-open it if you find an issue in state_machine.
