### ISSUE TITLE
[feature request] can_#{event} method should run validations

### ISSUE THREAD

**Issue by bradrobertson** [pluginaweek/state_machine#112]
On active_record objects, the state machine doesn't run validations when determining if an object can transition to a state.  This provides unexpected behaviour, as I would assume that `can_do_foo?` would return false if the validations fail.

Here's a simple example:

```
state :foo
  validate :fooable?
end

event :do_foo
  transition all => :foo
end

def foobale?
  errors.add(:base, "you can't do this")
  false
end

$ obj.can_do_foo?
# => true
$ obj.do_foo
# => false
```

**Comment by obrie** [comment]
HI Brad,

Thanks for commenting on this.  The truth is that there are several things that could prevent an event from transitioning, including:
- validation failures
- before callback halts (before_transition, before_save, etc.)
- rollbacks in any before / after callback

You'll truly never know if a transition will succeed until you actually attempt it.  If we were to make this helper a little more robust, the question becomes: which kinds of failures can it catch and is it obvious that it only catches those failures?  In addition, the only way to determine whether validations will pass is to actually change the value of the state field.  The act of changing the state has a pretty high potential of causing other unexpected side effects, especially when you call can_#{event}? in succession for multiple events.

Currently this helper is meant to answer one question: Is there a transition defined in the state machine that can transition from the current state to the next state ignoring object context?  If we make that question more complex, I think there are other subtle problems that we're going to encounter.

In your situation, I would consider whether you can just attempt to call `do_foo` without the need to check for `can_do_foo?`.  If there's logic for trying different events, I'd suggest that perhaps you can push that logic into the state machine.  If there's a specific reason you need to call `can_#{event}?` instead of just calling the event, I need to understand the use case to determine what we can do in state_machine to help.

A alternative you could consider with the current implementation is the following:

``` ruby
obj.state_event = 'do_foo'
if obj.valid?
  ...
else
  ...
end
```

What this does is the following:
1. Validate that a transition exists.  If it succeeds, make the transition to the new state.
2. Run the remaining validations on the object.  If the validations fail, the transition is rolled back.

Let me know your thoughts.

**Comment by bradrobertson** [comment]
ya that's a fair response.  I was just thrown off a bit because my assumption was that it would check these things.  I've already used a similar workaround above so there's no problems per se.  

I would make a specific mention in the docs that `can_#{event}` _only_ checks if the transition from one state to another is allowed and doesn't consider things like validations.

**Comment by obrie** [comment]
Thanks for the feedback!
