### ISSUE TITLE
multi-state validations workaround idea

### ISSUE THREAD

**Issue by jaylevitt** [pluginaweek/state_machine#116]
Why not override `validate` in the ActiveModel integration, as something like

```
def validate(validator)
  ActiveModel::Whatever::validate {|model| model.send(validator)}
end
```

**Comment by obrie** [comment]
Jay -

Thanks for the idea!  I'm actually making a few moves to get away from implementing unsupported workarounds / overrides that make it difficult to remain compatible with future versions of ORMs.  While something like this would likely solve the problem, it introduces a fairly brittle override that could come back to bite us in case the API changes or if there are any other libraries that expect the `validate` method to work according to the ActiveRecord implementation.

The other way you can solve this is by changing state_machine to only call `validate` once instead of for each state in the block.  However, my concern is that we'll inevitable run into the same problem.  There are going to be instances where users want to do something like so:

``` ruby
state_machine do
  state :parked, :idling do
    validate :some_validation_method, :if => lambda {|vehicle| vehicle.speed == 0}
  end

  state :first_gear, :second_gear, :third_gear do
    validate :some_validation_method, :if => lambda {|vehicle| vehicle.speed > 0}
  end
end
```

The example is contrived, but hopefully you get the idea.  The real fix here is for someone in the ActiveRecord community to advocate a change to `validate` to support this use case.  I haven't heard that anyone's suggested a fix to the ActiveRecord team yet.  It may be that the ActiveRecord core team doesn't accept the change and instead suggests that there are better ways of writing the validation... or that my example is contrived and there's no real reason anyone should have to use the same `validate` call in multiple `state` blocks.  I welcome that feedback and am sure it would push me in one direction or the other.

For now, however, I'd prefer to avoid core ActiveRecord overrides.  Please feel free to re-open or file a new pull request if there are further ideas.
