### ISSUE TITLE
Can't declare transition from nil

### ISSUE THREAD

**Issue by jaylevitt** [pluginaweek/state_machine#118]
I want to make sure I can't start an already-started survey, so I wrote:

```
class Survey < ActiveRecord::Base
  state_machine :state, :initial => nil do
    event :start do
      transition nil => :started
    end
  end
end
```

But although `:initial => nil` is the recommended idiom (since I need callbacks), I can't declare `transition nil => :started`. Yet if i say `transition all => :started`, I'm not guarding against calling `start` twice, or restarting a survey in some other state.

**Comment by obrie** [comment]
Hey Jay -

I can't seem to reproduce the issue you're seeing.  I did find one issue related to observer callbacks when using nil states which has since been fixed.  However, I haven't found any issues with running transitions.  I ran the following example on Ruby 1.8.7 / ActiveRecord 3.0:

``` ruby
class Survey < ActiveRecord::Base
  state_machine :state, :initial => nil do
    event :start do
      transition nil => :started
    end
  end
end

s = Survey.new  # => #<Survey id: nil, state: nil>
s.state         # => nil
s.started?      # => false
s.save          # => true
s.state         # => nil
s.started?      # => false
s               # => #<Survey id: 1, state: nil>
s.can_start?    # => true
s.start         # => true
s.state         # => "started"
s               # => #<Survey id: 1, state: "started">
```

Can you tell me exactly what error you're seeing?  If you can reproduce this, I'd love to see a test case for it.  Thanks!

**Comment by obrie** [comment]
Feel free to re-open if you're still seeing this.
