### ISSUE TITLE
observer - wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by pzupan** [pluginaweek/state_machine#119]
I'm getting this exception and have traced it to lib/state_machine/integrations/active_model/observer.rb.

In the update_with_multiple_args, it throws an exception when I state_machine attempts to run one of the after callbacks.  It seems to work on all but one, though I can't figure out why it won't work on the last as all the variables passed into the function seem to be complete.  Anyway, I've changed it as follows.  Let me know you think this might be a problem.

Was:

```
def update_with_multiple_args(observed_method, object, *args) #:nodoc:
      if args.any?
        send(observed_method, object, *args) if respond_to?(observed_method)
      else
        update_without_multiple_args(observed_method, object)
      end
end
```

I changed to:

```
  def update_with_multiple_args(observed_method, object, *args) #:nodoc:
      if respond_to?(observed_method)
        begin
          send(observed_method, object, *args)
        rescue
          update_without_multiple_args(observed_method, object) 
        end
      end
  end
```

**Comment by obrie** [comment]
Thanks for the heads up!  I actually just changed the Observer integration so that it no longer method chains #update.  This will fix any possible issues where observed methods were being called incorrectly.  Take a look at the change at https://github.com/pluginaweek/state_machine/commit/fe2b9beae938d8c400f53f7ed38bab26a6cc54d0.  This will be available in the next release.

The one thing to note is that all state_machine-related Observer hooks require two arguments: the record and the transition.

Hope this helps!
