### ISSUE TITLE
ActiveRecord::RecordInvalid being raised as StateMachine::InvalidTransition

### ISSUE THREAD

**Issue by austinthecoder** [pluginaweek/state_machine#138]
Consider the following code:

``` ruby
class Person < ActiveRecord::Base
  validates :name, :presence => true

  state_machine do
    state :awake

    event :wake do
      transition nil => :awake
    end
  end
end
```

When I run the following, I would expect `ActiveRecord::RecordInvalid` to be raised. Instead, `StateMachine::InvalidTransition` is raised:

``` ruby
Person.new(:name => nil).wake!
```

The record being invalid is the original reason why the state machine error is raised. Hiding this error can be confusing, especially when the error message is "Cannot transition state via :wake from nil". This message makes it seem like the state machine is not allowing the state to move from 'nil' to 'awake', via the 'wake' event.

Perhaps this is not a bug, but rather a coding preference. Thoughts?

**Comment by obrie** [comment]
Hey @soccer022483 -

Thanks for your feedback.  I think there's perhaps a little misunderstanding of what's happening under the hood when you call `wake` or `wake!`.  When using the default ActiveRecord configuration in state_machine, calling an event like `wake` results in the `save` method being called on your record once the state has transitioned.  As I'm sure you know, `save` will return true or false, depending on whether validations passed, the save occurred, etc.  The `wake` method will return true or false, depending on whether the transition is allowed, the `save` occurred, etc.

Now when you call `wake!`, the behavior of the method is very simple: call `wake` and raise an exception if false is returned.  At no point, is an `ActiveRecord::RecordInvalid` exception encountered.  However, you should instead be able to inspect the `errors` collection to see if there were any validation errors.

If you'd prefer, you _could_ control your state machine to always call `save!` like so:

``` ruby
class Person < ActiveRecord::Base
  state_machine :action => :save! do
    event :wake do
      transition nil => :awake
    end
  end
end
```

Now there are definitely caveats around overriding the action like this -- certain ActiveRecord-specific hooks around validations and callbacks become unavailable.

My recommendation is that if you want complete control over how `save` gets invoked, you use attribute-based events like so:

``` ruby
class Person < ActiveRecord::Base
  state_machine do
    event :wake do
      transition nil => :awake
    end
  end
end

# Uses save
p = Person.new
p.state_event = "wake"
p.save

# Uses save!
p = Person.new
p.state_event = "wake"
p.save!
```

Hope this helps!

**Comment by jeroenhouben** [comment]
I also spent a day debugging this issue. Why does StateMachine::InvalidTransition even exist? Isn't it just another validation? I mean, invoking an invalid transition could just throw a RecordInvalid with an error on the state column and the content being an i18n key like en.statemachine.invalid_transition. Just like any other validation error.

Or, maybe you can just include the original exception in the error message when raising StateMachine::InvalidTransition. It took me a long time to figure out some other column was invalid instead of the transition itself.

I do really like using this gem! (dont get me wrong ;-)

**Comment by obrie** [comment]
Hey @jeroenhouben -

Thanks for the feedback.  I definitely want to better understand what leads to the debugging difficulties.  What are your thoughts on the comment I added earlier to this issue?  Is your situation that the invalid column wasn't showing up in the list of errors on the record?  If so, I'd love to see an example so that I can reproduce it locally.  Even if state_machine throws an exception, any validation errors on the record should be kept around.

**Comment by jeroenhouben** [comment]
Hi obrie,

It seems that if I use the attribute-based events I can make transitions that I have not specified to be possible.. Or I'm doing something wrong..
Other than that, I like using state machine's bang! methods, they clearly show their intent.

class Invoice < ActiveRecord::Base

  state_machine :payment_state, :initial => :unpaid do

```
event :sent_to_psp do
  transition :unpaid => :sent_to_psp
end

event :paid do
  transition :sent_to_psp => :paid
end

event :payment_failed do
  transition :sent_to_psp => :failed
end

event :payment_canceled do
  transition :sent_to_psp => :canceled
end
```

  end
end

ruby-1.9.2-p290 :006 > i.payment_state = "unpaid"
 => "unpaid" 
ruby-1.9.2-p290 :007 > i.save!
 => true 

that should not be possible, right?

**Comment by obrie** [comment]
Attribute-based events involves setting an attribute to an event name that will fire when you save the record.  In this case, what you'd do is the following:

``` ruby
i.payment_state_event = "sent_to_psp"
i.save!
```

This will cause the `sent_to_psp` event to run.

**Comment by jeroenhouben** [comment]
Ah ok, I did not know you could do that. Yes that does throw a more helpful exception. Thanks for your help!

Still I think that it would be nice if the StateMachine::InvalidTransition class had an original_error field or something that would make it easier to track down the cause of the InvalidTransition.

**Comment by austinthecoder** [comment]
@obrie, in response to:

> when you call wake!, the behavior of the method is very simple: call wake and raise an exception if false is returned

I see that `wake` returns the result of calling `fire` on an event. So `wake!` raises an exception if false is returned from `fire`. My problem with this is that it looks like `fire` can return false for a couple different reasons: if there's no transition for the object, or if performing the object fails. So I think this is why the `StateMachine::InvalidTransition` error isn't very helpful in figuring out what the problem is. Now, your solution to this was:

> you should instead be able to inspect the errors collection to see if there were any validation errors.

I don't think exceptions should require additional investigation.

Here's a possibile refactor. Tell me what you think. What if `wake!` doesn't call `wake` but rather calls `fire!` on the event. Here's what `fire!` might look like:

``` ruby
def fire!(object, *args)
  machine.reset(object)

  if transition = transition_for(object)
    transition.perform!(*args)
  else
    on_failure(object)
    raise StateMachine::InvalidTransition.new(object, machine, name)
  end
end
```

So if the transition fails, we get `InvalidTransition`. I'm not sure if `perform!` exists, but obviously it would be similar to `perform`, except raising an error on failure. Thoughts?

**Comment by obrie** [comment]
I've re-opened this issue as I've been convinced that things could be improved here :)  I'll elaborate in a moment.

**Comment by obrie** [comment]
Hey guys -

So, as I mentioned, I was convinced that there must be a problem here and something that could be improved given the number of people I've heard this complaint from.  My interpretation and solution to the problem is perhaps different than you had imagined and I'll give a little insight into why I chose this path and not any of the others proposed.
- Why not use `save!` to and just rely on the ORM to throw the appropriate solution?

This is an interesting approach, but quickly breaks down for a variety of reasons.  First, I typically prefer consistency of state_machine behavior across ORM integrations.  By throwing different exceptions depend on the ORM being used or whether there's one used at all can make things confusing for folks crossing boundaries between ORMs.  Second, not all ORMs are going to define a `save!` version of their persistent method... state_machine needs to account for those situations.  Finally, I prefer to keep state_machine simple when it comes to determining what action gets called from an event.  When you start to introduce the concept of being able to execute different actions based on what event method was called, I think things are going to get confusing and complex quickly.
- Why not use `fire!` / `perform!` and throw a different exception for an unknown transition vs. a transition that failed to complete?

I won't deny that this is an interesting idea.  However, the current implementation of state_machine just doesn't provide an opportunity for it to be integrated.  First, I can't change `#{event}!` to not call `#{event}` -- this breaks a contract made for events that you can override the event method and not have to worry about when you call the bang vs. non-bang version.  While you could consider getting around that by having `#{event}!` pass an option like `:raise_on_faliure => true` to the normal event method, this is a significant API change that I don't want to take on.  I'd rather come up with a way to help solve the problem without introducing an interface-breaking change.

---

So with all this in mind, the solution I decided was the simplest and most effective was this: Include error reasons in the exception's message based on the validation errors on the object.  This brings the exception more in line with how ActiveRecord's `RecordInvalid` exception behaves (and likely other ORMs).

The prior behavior was thus:
- When an unknown transition was encountered, add a validation error to the object indicating that it's not valid
- When the action fails to save on a known transition (either because a validation error was encountered or a before_\* callback halted), do nothing but return false

Those behaviors are still true, but we use that information to provide error details in the `InvalidTransition` exception.  The implementation basically looks for validation errors on the object and, if there are any, includes them.  If there are no errors, a "Transition halted" reason is given - this means that a callback (whether in state_machine or AR) halted the execution.

It will still be the responsibility of whoever is defining the callbacks that halt execution to provide information about those failures, such as by adding a error to the object.

Take a look through the docs and tests -- there are some examples in there that should give you an idea of the types of exception messages you'll see.

Hopefully this helps make debugging easier going forward!  Thanks for following up.

**Comment by jeroenhouben** [comment]
Hi Obrie,

I read your reply and skimmed through the changes. This will work great for me. I basically wanted more descriptive errors and this change seems to provide just that. Great work, many thanks!!
