### ISSUE TITLE
Transition callbacks only called when defined within an Observer

### ISSUE THREAD

**Issue by jamesbebbington** [pluginaweek/state_machine#141]
[The docs](http://rubydoc.info/github/pluginaweek/state_machine/master/StateMachine/Integrations/ActiveRecord) only gives examples of specifying callbacks within an `ActiveRecord::Observer`. It would be most helpful if transition callbacks could also be defined on an `ActiveRecord::Base` class too as this would mirror the functionality available in rails. Is this by-design, a technical limitation or just something that hasn't been implemented?

Thanks.

**Comment by obrie** [comment]
Hi @fractious,

The callbacks are made available as methods in `ActiveRecord::Observer` because it's really the only way to hook into state_machine in observers.  On the other hand, you have `before_transition` / `after_transition` callbacks in the model which give you much greater flexibility for defining callbacks.  In fact, you could very well use those to generate a similar-looking method yourself like so;

``` ruby
state_machine do
  before_transition :parked => :idling, :on => :ignite, :do => :before_park_from_parked_to_idling
  ...
end
```

I prefer that folks use these flexible behaviors in state_machine and, instead, consider the Observer hooks just workarounds.  If you were to take a look at the way Observer hooks are implemented in the DataMapper integration, you'll notice that these methods aren't necessary at all -- you can just hook into the `before_transition` / `after_transition` helpers.

Hope this helps!

**Comment by jamesbebbington** [comment]
Hey @obrie, yeah that does help, thanks!
