### ISSUE TITLE
Validation inside of state block causes error [MongoMapper]

### ISSUE THREAD

**Issue by probablykabari** [pluginaweek/state_machine#143]
I haven't tested this outside of my app, but here's a snippet of the code:

``` ruby
  state_machine :status, :initial => :draft do

    state :published do
      validate :some_validation
    end

  # ....

    event :publish do
      transition [:draft] => :published
    end
  end
```

When I do this, validations run but the record is never marked as invalid if they fail (`valid?` returns true).  When using `publish!` I get:

```
StateMachine::InvalidTransition:
       Cannot transition status via :publish from :draft
```

Removing the validation makes everything work fine.

**Comment by obrie** [comment]
Hey @RipTheJackker -

Validations don't run until the state is entered.  If you call `valid?` prior to calling `publish!`, the validation won't run since the object isn't yet in the `published` state.  As well, if you upgrade to version 1.1.0, you'll find that the exception that gets raised also includes the failure reason (such as a failed validation).  If you inspect the object after calling `publish!` you should see the errors that were added from your `some_validation` method.

Hope this helps!
