### ISSUE TITLE
Initial state cannot be a string?

### ISSUE THREAD

**Issue by nathanl** [pluginaweek/state_machine#144]
I just stumbled on a behavior in state_machine that confuses me and I wondered if you could give some clarification.

I had the following code on an ActiveRecord model:

``` ruby
state_machine :status, :initial => 'requested' do

  event :approve do
    transition :requested => :approved
  end

  # more events here...
end
```

When I called `approve!`, I got `StateMachine::InvalidTransition: Cannot transition status via :approve from "requested" (Reason(s): Status cannot transition via "approve")`

While puzzling over this, I idly changed `:initial => 'requested'` to `initial => :requested` and was surprised that it started working.

I was calling this transition on a record that had been loaded from the database. Whether I had specified the initial status of the original object as a symbol or string, it was saved in the database as a string, and the new ActiveRecord object certainly pulled a string value out of the database. I don't see how it would "know" whether `status` on the original ActiveRecord object had been initialized with a symbol or string.

Is this behavior by design or is it a bug? I'm not even sure how I would do this if I wanted to. :)

**Comment by obrie** [comment]
Hi Nathan,

In state_machine definitions, all states are referenced by their name.  State names are typically referenced using symbols, although there are a few exceptions when states / events are coming from user input in the browser.  The string version of the name is what state_machine would refer to as the state's value.  So there are 2 properties associated with a state: it's name (a symbol) and it's value (the string version of the name, by default).  However, you could certainly imagine a scenario where you're using something other than strings for state values like so:

``` ruby
state_machine :status, :initial => :requested do
  state :requested, :value => 0
  state :approved, :value => 1
end
```

As you can see, the distinction between state names and their values is by design.  state_machine doesn't do anything special to convert names from strings to symbols or otherwise.  In theory, you could use strings as state names; however, this would need to be consistent across the entire state_machine definition.  Since you're mixing string names and symbol names, "requested" is considered to be a different state than :requested (again, every name is unique -- there's no conversion being done).

So the short answer is that this by design and the use of a symbol is what you should be doing for the definition.

Hope this helps!

Best,
Aaron

**Comment by nathanl** [comment]
Thanks for the detailed answer. Two follow-up questions:

1) Would you take patch with a tiny bit of documentation on this? For instance, "Note that state names are given as symbols. You may use strings, but you must be consistent: `:parked` is not the same state as `'parked'`.

2) This would be much harder, but it would be lovely to get an error message if there are "unconnected" states. For example: "Warning: there is no transition out of state `:parked`" or "Warning: there is no transition to state `:first_gear`".

**Comment by obrie** [comment]
1) Definitely - I haven't checked if there are already docs, but whether it's there or not, it's apparent that it should be made more obvious.

2) It's an interesting idea and certainly doable, but I think it's going to cause more problems than it solves.  There are definitely cases where states are defined because they used to be used, but aren't anymore -- so they're just there for historic reasons.  The first example represents a final state, so that's a perfectly valid scenario.  The second case is less likely, but I think we can provide a different solution.

Instead of warning when there are unconnected states, I think it would be useful to warn when there are different class types being used for state names (e.g. mixing both string and symbol names in a definition).  That seems like a much less likely scenario and something for which a warning would be warranted.
