### ISSUE TITLE
Excessive memory usage in rails

### ISSUE THREAD

**Issue by stevestmartin** [pluginaweek/state_machine#152]
We were seeing large amounts of CPU time spent in GC mainly due to object allocation when generating the call stack in NilClass#raise_nil_warning_for  in ActiveSupport's whiny_nil implementation. 

I tracked it back to initializing [callbacks](https://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/callback.rb#L129) where it is apparently calling

``` ruby
Array(nil)
```

triggering a

``` ruby
nil.to_ary 
```

causing the exception (which i think are just being swallowed). While this issue is mainly do to the whiny_nil implementation which is being removed from future rails versions, simply changing 

``` ruby
Array(options.delete(:do))
```

to 

``` ruby
Array(options.delete(:do) || []) 
```

would remove the issue for everyone.

**Comment by obrie** [comment]
Hey @stevestmartin -

Thanks for reporting this.  It looks like this has already been fixed in the Rails 3-1-0-stable branch.  See https://github.com/rails/rails/commit/d1abf29e796a86cbac315da217f3fe7addb88106.  I suspect we'll see an official tagged release with it soon.

Since there are likely many other libraries that could be causing this issue as well, I'd prefer that folks on Ruby 1.9+ either upgrade their Rails installation or backport the patch.
