### ISSUE TITLE
Transitions and conditions

### ISSUE THREAD

**Issue by tanelsuurhans** [pluginaweek/state_machine#155]
I have a state machine as follows:

``` ruby

event :advance_to_ordered do
  transition :to => :ordered
end

event :advance_to_locked do  
  transition :to => :locked
end

event :advance_to_complete do
  transition :to => :completed
end

after_transition :from => :ordered, :to => :locked, :do => :foo
after_transition :from => :ordered, :to => :completed, :do => :foo
```

I'm assuming that the transition hooks should only fire when going from :ordered to :locked or :ordered to :completed, right?
And not fire when going from let's say :locked to :locked etc.
But the thing is that even when i'm doing :advance_to_locked while being in the :locked state, the first transition callback gets called. I tried the option :except_from too, no dice. Is this supposed to work like that?

**Comment by obrie** [comment]
Hi @tanelsuurhans -

I'm not seeing the same behavior.  See below:

``` ruby

require 'rubygems'
require 'state_machine'

class Vehicle
  state_machine do
    event :advance_to_ordered do
      transition :to => :ordered
    end

    event :advance_to_locked do  
      transition :to => :locked
    end

    event :advance_to_complete do
      transition :to => :completed
    end

    after_transition :from => :ordered, :to => :locked, :do => :foo
    after_transition :from => :ordered, :to => :completed, :do => :foo
  end

  def foo
    raise ArgumentError
  end
end

v = Vehicle.new       # => #<Vehicle:0x8fafcb4 @state=nil>
v.state = 'locked'    # => "locked"
v.state               # => #<Vehicle:0x8fafcb4 @state="locked">
v.advance_to_locked   # => true
v                     # => #<Vehicle:0x8fafcb4 @state="locked">
v.state = 'ordered'   # => "ordered"
v.advance_to_locked   # => ArgumentError: ArgumentError
```

Notice that a transition from `:locked` to `:locked` does not result it any errors.  Are you sure there are no other transitions or callbacks being defined that might be calling `:foo`?  Is there anything else interesting in the class or state machine?  I have to imagine that there's something else in the environment going on that's causing this.  Can you try this in a simple app that demonstrates the issue so that I could perhaps try it as well?

**Comment by obrie** [comment]
Closing this.  Feel free to re-open if you've found further evidence suggesting an issue within state_machine.
