### ISSUE TITLE
Initial state as lambda is not working in ActiveRecord-3.1.1

### ISSUE THREAD

**Issue by a-chernykh** [pluginaweek/state_machine#174]
Hi,

Just noticed that this works:

`state_machine :state, :initial => :pending do`

but this don't:

`state_machine :state, :initial => lambda {|r| :pending} do`

It does not sets the initial state to 'pending', but sets the initial state from the default column value for new object.

Andrey.

**Comment by a-chernykh** [comment]
that's only valid if column has default value set

**Comment by obrie** [comment]
Hey @AndreyChernyh -

Thanks for reporting this.  Unfortunately there's not much state_machine can do here.  To help debug issues like this in the future, I've added a change that causes a warning to be generated when the situation is detected.

The core issue is that static initial states get set prior to the remaining initialization of the record and dynamic initial states (like the one in your example) get set _after_ the record has been initialized.  There's really no reliable way to know that state_machine should ignore the existing value set for the state attribute and use the dynamic initial state defined.

My recommendation is to avoid the situation - if you're going to use state_machine to set the initial state, only do so there... otherwise you need to rely on the database defaults and any of your own custom initialization code.

Hope this helps!
