### ISSUE TITLE
Conditional view rendering

### ISSUE THREAD

**Issue by cpeters** [pluginaweek/state_machine#187]
Hi,

I have expanded upon the base state machine and developed a feature that allows me to render view partials based upon the current `state` and the events available for the current state. This has allowed me to create dynamic navigation to specific partials with minimal code.

Would these feature be something that you would like to add to the project?

Thanks,
Chris

**Comment by obrie** [comment]
Hi Chris -

It's a great idea and I appreciate you taking the time to propose the feature.  My feeling is that this is the type of feature that I'd prefer to keep outside of the core and released as an individual gem.  You can take a look at other gems like state_machine-audit_trail which provide similar extensions that are outside of the core's responsibilities.

If it turns out this is something that is wanted by the large proportion of state_machine's users, I'd happily reconsider it.

Thanks!
