### ISSUE TITLE
state and state_name logically the wrong way round?

### ISSUE THREAD

**Issue by joehorsnell** [pluginaweek/state_machine#207]
Hi,

Intuitively it feels to me like state and state_name are the wrong way round, i.e. state returns a string and state_name a symbol, but in the state machine definitions the recommended practice (according to the docs) is to use symbols for the states, so it's almost always state_name that you want, not state.

It's not a biggie, I just wondered if this was something anyone else had raised? I couldn't find any similar issues at least.

Thanks for producing a great tool.

Joe.

**Comment by the8472** [comment]
If you're talking about the instance level methods then `.state` accesses the value as if the state machine wasn't there. I.e. it's the value, which might get stored in a database etc. The state_name is the name of the current state as seen from the perspective of the state machine (which can be accessed on the class level) instead of the object instance.

That's how I see it, working a lot with the class level representation (which is more powerful but less concise) instead of the instance helper methods.

**Comment by joehorsnell** [comment]
Ok, thanks for clarifying.
