### ISSUE TITLE
valid_in_state?

### ISSUE THREAD

**Issue by suung** [pluginaweek/state_machine#212]
Iit took me a while to realise that can_event? does not run the validations for the state and oinly looks for existing transition definitions (correct?)

We have a implementation called

```
def valid_in_somestate?
  self.state = "somestate"
   valid?
end
```

to realize a setup where

```
transition :foo => :bar, :if => :valid_in_some_state? # :if  => :can_some_state_event?
```

useful? if so i would implement it

**Comment by the8472** [comment]
can_event? only checks the branch requirements and if/unless conditions, you can't accurately predict whether something will be valid after a complete transition since
a) validations may be complex
b) before/after handlers may perform complex modifying actions

Those combined make it nearly impossible to see if a transaction would actually succeed in advance, especially if something the handlers do it not idempotent/cannot be rolled back.

So you'll always have to compromised in your advance checks some way or another. I would recommend using the after/before handlers more to simply abort the transition when the need arises, and recording the error state while doing so and then analyze/display the errors if that failed.

Since transitions are transitory (heh) i wrote a persistent_errors extension that does not re-run the validations on every call to valid? but pins the object as an invalid until they are cleared explicitly, this allows me to attempt transitions, display meaningful errors on failure and then try them again once the input errors have been corrected.

**Comment by obrie** [comment]
I agree with @the8472 here -- running validations has very real side effects especially if you begin to consider instances where you're using event attributes.  Event attributes get processed prior to validation, meaning that if you were to attempt validation the event would get processed and the state would get transitioned.  Also note that sometimes validations depend on the current state of the record.

For these reasons I tend to avoid worrying about validations when it comes to determining whether an event is possible.

**Comment by robotfelix** [comment]
I think @suung's suggestion would be very useful - although the implementation should return the state attribute back to its original value after the validations are run.

I don't really understand your counter arguments @obrie and @the8472: while it won't necessarily work as expected in complex scenarios, it will work in every situation that `valid?` will.

As a user I wouldn't expect this function to handle all the complexities of my state machine, I just need a way of running the validations associated with a given state. @suung's method name is right on the money here, it's not asking `can_event_occur_given_validations?`, just whether the object is (or would be) `valid_in_state?`. Determining whether an event is possible is a different question entirely!

**Comment by suung** [comment]
sorry, I did not realize there are anwers.

This suggestion is not a fancy idea but something that 

a) happens in practice
b) has to be worked around and
c) exists in several projects I know

I don't understand the argument 'validations are complex'. They are run by valid, they exist anyway, you expect them to work in the next state anyway and fail if not valid.

I might understand the argument 'have side effects' but due to the heat i fail to make up an example with side effects. Side effects would mean for me: Should be run only once. Validations that can be run only once are very problematic in rails.

To clarify my reason again:

State machine should - in my humble opinion - have a better logic to maintain the control flow, like displaying a button NOT if clicking it would fail.

Of course you can handle the exception and so on.

cheers

**Comment by the8472** [comment]
> like displaying a button NOT if clicking it would fail.

If that's your issue... that's what the from states and the if/unless conditions are for. Those are things under the control of the state machine. Validations are part of the underlying model and the restrictions they impose cannot be anticipated by the state machine. Therefore the state machine does not know what `valid_in_state?` means.

Example:

``` ruby
state_machine do

  state :b do
    validates_presend_of :foo
  end

  event :bar do
    transition :a => :b, :if => lambda{|o| o.something?}
  end

  before_transition do |o,t|
    o.foo = t.args.last[:foo]
  end
end
```

How is `valid_in_state?(:b)` supposed to work here? The transition from a to b would succeed, but the statemachine cannot know that. it can only know that the something precondition has to be fulfilled.

Validations essentially are postconditions. Postconditions can only be verified after the event has been executed, not before.

**Comment by robotfelix** [comment]
@the8472 I still think you're missing the point - which is to run validations. Your example does indeed show a situation where `valid_in_state?` doesn't tell us whether the model can transition to `:b`, but that's not what validations are for.

We can easily code up an example where `valid?` succeeds but `save` fails.

```
before_save :block_anyway
def block_anyway
  return false
end
```

`valid?` will not always guarantee that an event will succeed, just as it cannot guarantee a save will succeed. This does not stop `valid?` still being useful in many situations, as a way of running validations and populating the `errors` object.

Let us change your example a little:

```
state_machine do

  state :b do
    validates_presence_of :foo, :number
    validates_format_of :number, :with => /\d*/
  end

  event :bar do
    transition :a => :b, :if => lambda{|o| o.something?}
  end

  before_transition do |o,t|
    o.foo = t.args.last[:foo]
  end
end
```

Now, before running event `:bar` we may want a way of knowing whether `:number` is in the right format. A `valid_in_state?` function would make it significantly easier to do this, and would allow us to populate the `errors` object.

**Comment by the8472** [comment]
> Now, before running event :bar we may want a way of knowing whether :number is in the right format.

But that information is useless, because the `before_transition` handler will change the `.foo` field.

If you only want to run validators for a different state then that is orthogonal to the state machine. It does not involve events, it does not involve transition-preconditions.

Just clone the object, set the state on it and validate. Or don't clone, set state, validate, reset state.

What you want is "what if"-validations to try out changing some field. That is not related to the state_machine gem at all.
