### ISSUE TITLE
ignores update_column

### ISSUE THREAD

**Issue by dougc84** [pluginaweek/state_machine#227]
My situation is this, and I had to create a very non-elegant solution to get this out the door:

I have a reservations model, and I let admins transition a reservation to several states that I'm not allowing a standard user to see.  The model itself is very complicated and has around 20 different validations.  One event I have set up is "extend_reservation," which takes the reservation's end date, calculates the next available date on the calendar (some reservations are weekly, biweekly, 3x a week, etc.).

In a before_transition callback (after_transition does the same), I want to call update_column on the model to bypass some validations I have set up so the users do not create overlapping reservations.  However, when I call update_column, it acts like I'm setting the attributes and saving normally, instead of manually setting each column's value, it rolls back, I get an error, and nothing is accomplished.

Here's a code example:

``` ruby
after_transition any => :extended do |reservation, transition|
  reservation.update_column :extension_count, (reservation.extension_count + 1)
  reservation.update_column :reservation_end_date, reservation.next_extension_date
end
```

My other validations trigger, and wham, nothing happens.  The same thing happens with before_transition as well.

If you need additional details, please let me know.  Thanks!

**Comment by obrie** [comment]
What's the error that you're getting?  You also need to be careful about what the call to `update_column` returns -- if it returns `false` and you're running within a `before_transition` callback, that can cause the entire process to halt.

The reason `before_transition` won't work here is because validations get run _after_ `before_transition` callbacks are invoked -- as a result, changes to those attributes will end up getting validated.

`after_transition` will work and I've verified this with a basic test:

``` ruby
class Vehicle < ActiveRecord::Base
  validates_inclusion_of :name, :in => %w(a b c)

  state_machine :initial => :parked do
    event :ignite do
      transition :parked => :idling
    end

    after_transition :parked => :idling do |vehicle, transition|
      vehicle.update_column :name, 'd'
    end
  end
end

vehicle = Vehicle.new   # => #<Vehicle id: nil, state: "parked", name: nil>
vehicle.name = 'a'
vehicle.save!           # => true
vehicle                 # => #<Vehicle id: 1, state: "parked", name: "a">
vehicle.ignite!         # => true
vehicle                 # => #<Vehicle id: 1, state: "idling", name: "d">
```

If you haven't already figured out the underlying issue, I'd suggesting looking at any other callbacks you have in place and see if there's a possibility either the record is getting saved again (and therefore failing validation) or something else is interacting with the save process in an unexpected manner.
