### ISSUE TITLE
Assign state as symbol doesn't work with boolean methods like state?(<some_state>)

### ISSUE THREAD

**Issue by arieliten** [pluginaweek/state_machine#240]
Here's a simple AR class with state_machine setup.

``` ruby
class Event < ActiveRecord::Base
  attr_accessible :state

  state_machine :state, :initial => :draft do
    event :publish do
      transition :draft => :published
    end
    event :cancel do
      transition :published => :canceled
    end
    event :reset do
      transition [:published, :canceled] => :draft
    end
  end

end
```

If I do this on console:

``` ruby
>> e = Event.new(state: :draft) #=> #<Event id: nil, state: :draft>
>> e.state  #=> :draft
>> e.draft?  #=> false
>> e.state?('draft')  #=> false
>> e.state?(:draft)  #=> false

```

So I think that the only way it works if I ensure that the state I assign (manually or via mass-assignment) is a string and not a symbol.

The documentation says:

```
There is an exception to this rule. The consistency is only required within the definition itself. However, when the machine's helper methods are called with input from external sources, such as a web form, state_machine will map that input to a String / Symbol
```

and it shows the following example:

``` ruby
v = Vehicle.new     # => #<Vehicle:0xb71da5f8 @state="parked">
v.state?('parked')  # => true
v.state?(:parked)   # => true
```

Any clue?

**Comment by obrie** [comment]
Hi @arieliten -

All state values are assumed to be strings unless otherwise specified.  When you call `v.state?(:parked)`, state_machine is looking up the state named `:parked` comparing it's associated value (`"parked"`) against the current state's value.  If you wish to use symbols instead of strings as your state values, you'll have to be explicit about it -- I've clarified this in the README via ba355a8.

**Comment by arieliten** [comment]
Thanks for the clarification @obrie

**Comment by the8472** [comment]
> is looking up the state named :parked comparing it's associated value ("parked") 

Maybe it should be clarified when a method expects the _value_ of a state or its _name_. E.g. if you do some programmatic checks it often makes more sense to check against the state name rather than its persistence representation, at least that's what I think.

I also often run into the situation where i ponder whether i should be using machine.name or machine.attribute when reflecting on state machines (i'm doing a lot of dynamic stuff requiring me to do reflection to build views).

**Comment by obrie** [comment]
There are no methods that expect to be looking at a value except for the actually attribute setter.  state_machine deals strictly with state names.
