### ISSUE TITLE
Exceptions not throw

### ISSUE THREAD

**Issue by maxime-d** [pluginaweek/state_machine#243]
Why doesn't have a exceptions where validation constraints is not validate.

Ex : validates :file_remote_url, :presence => true, :unless => lambda { |b| b.creation_basic? || b.creation_upload? || b.creation_pdf? || b.creation_epub? }

event(:creation_pdf_uploaded) { transition :creation_pdf => :creation_cover }

This event creation_pdf_uploaded don't throw exceptions.

**Comment by the8472** [comment]
It returns false.

**Comment by maxime-d** [comment]
Yes it's return ROLLBACK, but we don't have a visibility on the errors. I have passed 3 hours for find this :(

**Comment by obrie** [comment]
@maxime-d The errors are available in `#errors` as they normally would.  state_machine doesn't really do anything particularly special here.  The record will fail validation, return false, and display errors in `#errors`.

If you're seeing otherwise, can you share a working example that I can run locally?  Thanks!
