### ISSUE TITLE
Setting boolean column as false causes error

### ISSUE THREAD

**Issue by PatrickMcSweeny** [pluginaweek/state_machine#258]
I have a model with a boolean column and if I try to assign a boolean value of false to it an error gets thrown and the object does not get saved if I have a state machine running on that column. 

If I remove the state machine from that same column, I can assign a value of false to that same column with no error so this bug seems to be specific to this gem.

**Comment by janetruluck** [comment]
Having the state machine on a column that is of type boolean may be causing this issue if you are not setting the value for the state. Your column type should be of type string so the states can be expressed if not. The goal of the state machine is to avoid having to gather the state of your object through numerous boolean fields in the DB so you may want to reconsider that column if it affects the state and instead roll it into the state machine. Otherwise, if it is for something else it may be easier just to add another column to manage the state and then leave that one for whatever purpose you have.

**Comment by PatrickMcSweeny** [comment]
Thanks for clearing that up. Maybe this could be stated more clearly in the documentation.

**Comment by detournemint** [comment]
Seems like this could be closed.
