### ISSUE TITLE
Update README - too complex

### ISSUE THREAD

**Issue by edusantana** [pluginaweek/state_machine#262]
Hi, please don't understand this message as bad one. I didn't liked to read the README. Since there are others like me around, i wrote this.

---

This is a difficult example (Vehicle) to understand when you don't use English as your native language, too many uncommom words:

-tow
-ignite (this is easy, but not commom)
-around_transition do |vehicle, transition, block|
  What's the meanning of around_transition?
-idling??
-stalled?

attr_accessor :seatbelt_on, :time_used, :auto_shop_busy
- it should have comment on them, we are already trying to learn a new plugin, comments explaining these will help to do so.

transition [:idling, :first_gear] => :parked
- it doesn't mean any thing for me.
- "Idle (idling) is a term which generally refers to a lack of motion and/or energy."

So idling is... the car is still, it doesn't move. Then.. the transition is "put the first gear" => result is parked??? See what I mean?

event :ignite do
  transition :stalled => same, :parked => :idling
end
This is not something that makes sense for me when i'm reading it for the first time. `same`?
"stall: It is commonly applied to the phenomenon whereby an engine abruptly ceases operating and stops turning."

I think if you are going to use this example, just write the history explaining it. Tell an story about the car before the code.

I usually don't have problem reading english, just for writing. well... when it's technical texts.

See also: http://stackoverflow.com/questions/8665037/best-example-or-tutorial-to-implement-state-machine-in-rails-using-state-machine

I'm learning state-machine from here: http://gistflow.com/posts/679-state-machine-with-rails-basics

**Comment by the8472** [comment]
> This is a difficult example (Vehicle) to understand when you don't use English as your native language

English is not my first language and I find those examples to be quite trivial. Not significantly more complex than usual Cat-is-subclass-of-Animal examples you find in OOP-programming courses for example.

My understanding is that the Vehicle is supposed to be an analogy for those familiar with the basic concept of a car, and those really are rather basic verbs, which usually are taught in school.

Anyway, if the example is not intuitive enough for you due to language issues, there also is more in-depth, technical  documentation which might allow you to understand it more easily by re-stating things in multiple ways: http://rdoc.info/github/pluginaweek/state_machine/master/frames/StateMachine/Machine

**Comment by edusantana** [comment]
Thanks, I will look at the link.

http://blog.envylabs.com/post/29045466981/the-rails-state-machine
